BL2_LEVELS_TO_TRAVEL_STATION_MAP = {
    'Ash_P': 'Eridium Blight',
    'BackBurner_P': 'The Backburner',
    'BanditSlaughter_P': 'Fink\'s Slaughterhouse',
    'Boss_Cliffs_P': 'The Bunker',
    'Boss_Volcano_P': 'Vault of the Warrior',
    'CastleExterior_P': 'Hatred\'s Shadow',
    'CastleKeep_P': 'Dragon Keep',
    'Cove_P': 'Southern Shelf - Bay',
    'CraterLake_P': 'Sawtooth Cauldron',
    'CreatureSlaughter_P': 'Natural Selection Annex',
    'Dark_Forest_P': 'The Forest',
    'Dead_Forest_P': 'Immortal Woods',
    'Distillery_P': 'Rotgut Distillery',
    'Docks_P': 'Unassuming Docks',
    'DungeonRaid_P': 'The Winged Storm',
    'Dungeon_P': 'Lair of Infinite Agony',
    'Easter_P': 'Wam Bam Island',
    'FinalBossAscent_P': 'Hero\'s Pass',
    'Fridge_P': 'The Fridge',
    'Frost_P': 'Three Horns Valley',
    'Fyrestone_P': 'Arid Nexus - Boneyard',
    'GaiusSanctuary_P': 'Paradise Sanctum',
    'Glacial_P': 'Claptrap\'s Place / Southern Shelf',
    'Grass_Cliffs_P': 'Thousand Cuts',
    'Grass_Lynchwood_P': 'Lynchwood',
    'Grass_P': 'The Highlands',
    'Helios_P': 'Helios Fallen',
    'Hunger_P': 'Gluttony Gulch',
    'HypInterlude_P': 'Friendship Gulag',
    'HyperionCity_P': 'Opportunity',
    'Ice_P': 'Three Horns Divide',
    'Interlude_P': 'The Dust',
    'Iris_DL1_P': 'Arena',
    'Iris_DL1_TAS_P': 'Arena',
    'Iris_DL2_Interior_P': 'Pyro Pete\'s Bar',
    'Iris_DL2_P': 'The Beatdown',
    'Iris_DL3_P': 'Forge',
    'Iris_Hub2_P': 'Southern Raceway',
    'Iris_Hub_P': 'Badass Crater of Badassitude',
    'Iris_Moxxi_P': 'Badass Crater Bar',
    'Luckys_P': 'The Holy Spirits',
    'Mines_P': 'Mines of Avarice',
    'OldDust_P': 'Dahl Abandon',
    'Orchid_Caves_P': 'Hayter\'s Folly',
    'Orchid_OasisTown_P': 'Oasis',
    'Orchid_Refinery_P': 'Washburne Refinery',
    'Orchid_SaltFlats_P': 'Wurmwater',
    'Orchid_ShipGraveyard_P': 'The Rustyards',
    'Orchid_Spire_P': 'Magnys Lighthouse',
    'Orchid_WormBelly_P': 'The Leviathan\'s Lair',
    'Outwash_P': 'The Highlands - Outwash',
    'PandoraPark_P': 'Wildlife Exploitation Preserve',
    'Pumpkin_Patch_P': 'Hallowed Hollow',
    'ResearchCenter_P': 'Mt. Scarab Research Center',
    'RobotSlaughter_P': 'Ore Chasm',
    'Sage_Cliffs_P': 'Candlerakk\'s Crag',
    'Sage_HyperionShip_P': 'H.S.S. Terminus',
    'Sage_PowerStation_P': 'Ardorton Station',
    'Sage_RockForest_P': 'Scylla\'s Grove',
    'Sage_Underground_P': 'Hunter\'s Grotto',
    'SanctIntro_P': 'Fight for Sanctuary',
    'Sanctuary_Hole_P': 'Sanctuary Hole',
    'Sanctuary_P': 'Sanctuary',
    'SandwormLair_P': 'Writhing Deep',
    'Sandworm_P': 'The Burrows',
    'SouthernShelf_P': 'Southern Shelf',
    'SouthpawFactory_P': 'Southpaw Steam & Power',
    'Stockade_P': 'Arid Nexus - Badlands',
    'TempleSlaughter_P': "Murderlin's Temple",
    'TestingZone_P': 'The Raid on Digistruct Peak',
    'ThresherRaid_P': 'Terramorphous Peak',
    'TundraTrain_P': 'End of the Line',
    'VOGChamber_P': 'Control Core Angel',
    'Village_P': 'Flamerock Refuge',
    'Xmas_P': 'Marcus\'s Mercenary Shop',
    'caverns_p': 'Caustic Caverns',
    'dam_p': 'Bloodshot Stronghold',
    'damtop_p': 'Bloodshot Ramparts',
    'icecanyon_p': 'Frostburn Canyon',
    'tundraexpress_p': 'Tundra Express',
}
